export const teamNameMap = {
    "Arizona Cardinals": ['ARI', 'ARZ', 'AZ'],
    "Atlanta Falcons": ['ATL'],
    "Baltimore Ravens": ['BAL', 'BLT'],
    "Buffalo Bills": ['BUF'],
    "Carolina Panthers": ['CAR'],
    "Chicago Bears": ['CHI'],
    "Cincinnati Bengals": ['CIN'],
    "Cleveland Browns": ['CLE', 'CLV'],
    "Dallas Cowboys": ['DAL'],
    "Denver Broncos": ['DEN'],
    "Detroit Lions": ['DET'],
    "Green Bay Packers": ['GB', 'GBP'],
    "Houston Texans": ['HOU', 'HST'],
    "Indianapolis Colts": ['IND'],
    "Jacksonville Jaguars": ['JAX'],
    "Kansas City Chiefs": ['KC', 'KCC'],
    "Las Vegas Raiders": ['LV', 'LVR', 'OAK'],
    "Oakland Raiders": ['LV', 'LVR', 'OAK'],
    "Los Angeles Chargers": ['LAC', 'LA', 'SD', 'SDC'],
    "San Diego Chargers": ['LAC', 'LA', 'SD', 'SDC'],
    "Los Angeles Rams": ['LAR', 'LA', 'STL', 'SL'],
    "St. Louis Rams": ['LAR', 'LA', 'STL', 'SL'],
    "Miami Dolphins": ['MIA'],
    "Minnesota Vikings": ['MIN'],
    "New England Patriots": ['NE', 'NEP'],
    "New Orleans Saints": ['NO', 'NOS'],
    "New York Giants": ['NYG', 'NY'],
    "New York Jets": ['NYJ', 'NY'],
    "Philadelphia Eagles": ['PHI'],
    "Pittsburgh Steelers": ['PIT'],
    "San Francisco 49ers": ['SF', 'SFO'],
    "Seattle Seahawks": ['SEA'],
    "Tampa Bay Buccaneers": ['TB', 'TBB'],
    "Tennessee Titans": ['TEN'],
    "Washington Commanders": ['WAS', 'WSH'],
    "Washington Redskins": ['WAS', 'WSH'],
    "Washington": ['WAS', 'WSH'],
}

export const teamAbbreviationMap = {
    'BAL': "Ravens",
    'PIT': "Steelers",
    'IND': "Colts",
    'HOU': "Texans",
    'CIN': "Bengals",
    'CLE': "Browns",
    'DET': "Lions",
    'MIN': "Vikings",
    'TEN': "Titans",
    'JAX': "Jaguars",
    'NE': "Patriots",
    'NYJ': "Jets",
    'NO': "Saints",
    'ATL': "Falcons",
    'CAR': "Panthers",
    'TB': "Buccaneers",
    'GB': "Packers",
    'CHI': "Bears",
    'LV': "Raiders",
    'DEN': "Broncos",
    'NYG': "Giants",
    'PHI': "Eagles",
    'ARI': "Cardinals",
    'SEA': "Seahawks",
    'LAC': "Chargers",
    'KC': "Chiefs",
    'SF': "49ers",
    'LAR': "Rams",
    'DAL': "Cowboys",
    'WSH': "Commanders",
    'MIA': "Dolphins",
    'BUF': "Bills",
};
